export const sintomas = [
  "Fiebre",
  "Dolor de cabeza",
  "Dolor muscular",
  "Vómito",
  "Náuseas",
  "Dolor articular",
  "Erupción cutánea",
  "Dolor abdominal",
  "Leucopenia",
  "Tos",
  "Cough",
  "Hiperemia faríngea",
  "Dolor retroocular",
  "Diarrea",
  "Fatiga",
  "Sangrado",
  "Hematocrito",
  "Hepatomegalia",
  "Pérdida del apetito",
  "Escalofríos",
  "Petequias",
  "Adenoides",
  "Taquicardia",
  "Aftas",
  "Comezón",
  "Estreñimiento",
  "Alteración de la conciencia",
  "Presión baja",
  "Sangrado al evacuar",
  "Extravasación",
  "Sangrado de mucosas",
  "Taquipnea",
  "Hipersensibilidad cutánea",
  "Exantema maculopapular",
  "Edema",
  "Molestias al orinar",
  "Choque",
  "Conjuntivitis",
  "Dolor lumbar",
  "Dolor de garganta",
  "Eritema",
  "Letargo",
  "Malestar general",
  "Rinorrea",
  "Sensibilidad a la luz",
  "Adenopatías",
  "Dolor al tragar",
  "Dolor generalizado",
  "Ardor en la piel",
  "Mareos",
  "Vértigo",
  "Difícultad respiratoria",
  "Transtorno del sueño",
  "Transtorno de concentración",
  "Mal sabor de boca",
  "Lesión renal aguda",
  "Disminución de orina",
  "Convulsiones",
  "Congestión nasal",
  "Rinitis",
  "Flemas",
  "Sibilancias",
  "Dolor torácico",
  "Inflamación de oído",
  "Estornudos",
  "Pérdida del olfato",
  "Pérdida del gusto"
];